# Generated by Django 5.0.4 on 2024-04-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-created"],
                "verbose_name": "услуга",
                "verbose_name_plural": "услуги",
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="required",
        ),
        migrations.AddField(
            model_name="service",
            name="requirements",
            field=models.TextField(
                default=123,
                help_text="Укажите что требуется от заказчика услуги. Например, ТЗ, доступы, и т.п.",
                max_length=500,
                verbose_name="от покупателя нужно",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                help_text="Подробное описание предрставляемой услуги",
                max_length=1200,
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="options",
            field=models.TextField(
                blank=True,
                help_text="Если вы предлагаете дополнительные услуги, расскажите о них. Укажите название, срок, стоимость.",
                max_length=1200,
                null=True,
                verbose_name="дополнительные услуги",
            ),
        ),
    ]
