# Generated by Django 5.0.4 on 2024-04-26 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_options_remove_service_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                default=1,
                help_text="Пользователь, который предоставляет данную услугу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
                verbose_name="исполнитель услуги",
            ),
            preserve_default=False,
        ),
    ]
