# Generated by Django 5.0.4 on 2024-04-26 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["id"],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="баланс"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="город"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="страна"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=1200,
                null=True,
                verbose_name="информация о вас и вашем опыте",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="телефон"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32, verbose_name="ваши навыки"),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="speciality",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="вы по специальности"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/profiles/",
                verbose_name="изображение профиля",
            ),
        ),
    ]
