# Generated by Django 5.0.4 on 2024-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_phone_alter_customuser_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1200,
                null=True,
                verbose_name="информация о вас и вашем опыте",
            ),
        ),
    ]
