# Generated by Django 5.0.4 on 2024-04-28 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="название")),
                (
                    "description",
                    models.TextField(
                        help_text="Опишите, что именно вам нужно, в каком объеме и за какой срок.",
                        max_length=5200,
                        verbose_name="детальное описание задачи",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="Ваш бюджет в руб.", verbose_name="цена не более"
                    ),
                ),
                (
                    "is_higher_price_allowed",
                    models.BooleanField(
                        default=False,
                        verbose_name="Готов рассмотреть предложения с ценой выше, если уровень исполнителя будет выше",
                    ),
                ),
                (
                    "max_price",
                    models.IntegerField(
                        blank=True,
                        help_text="Максимальная цена в случае высокого уровня исполнителя.",
                        null=True,
                        verbose_name="максимальная цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы исключить проект из каталога, не удаляя его.",
                        verbose_name="проект активен",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменен"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Категория, в которой будет размещен проект",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="exchange.category",
                        verbose_name="рубрика",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Пользователь, который предлагает данный проект для реализации",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="заказчик проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "проект",
                "verbose_name_plural": "проекты",
                "ordering": ["-created"],
            },
        ),
    ]
