# Generated by Django 5.0.4 on 2024-04-30 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Комментарий кандидата для заказчика касательно проекта.",
                        max_length=500,
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создано кандидатом"),
                            ("declined", "Отклонено заказчиком"),
                            ("cancelled", "Отменено кандидатом"),
                            ("accepted", "Принято заказчиком"),
                        ],
                        default="created",
                        max_length=32,
                        verbose_name="статус предложения",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменен"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="Пользователь, который предлагает свои услуги для реализации проекта.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кандидат на выполнение проекта",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="projects.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "предложение",
                "verbose_name_plural": "предложения",
                "ordering": ["-created"],
            },
        ),
    ]
