# Generated by Django 5.0.4 on 2024-04-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Предложение отменено или отклонено.",
                verbose_name="отменено",
            ),
        ),
    ]
