# Generated by Django 5.0.4 on 2024-04-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                (
                    "price",
                    models.IntegerField(
                        help_text="Стоимость заказа в руб.", verbose_name="стоимость"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Размещен заказчиком"),
                            ("in_progress", "В работу у исполнителя"),
                            ("cancelled_by_customer", "Отменен заказчиком"),
                            ("cancelled_by_provider", "Отменен исполнителем"),
                            ("submitted_by_provider", "Сдан исполнителем"),
                            (
                                "returned_by_customer",
                                "Возвращен заказчиком на доработку",
                            ),
                            ("accepted_by_customer", "Принят заказчиком"),
                            ("paid", "Оплачен"),
                            ("completed", "Завершен"),
                        ],
                        default="created",
                        max_length=32,
                        verbose_name="статус заказа",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="комментарий к заказу",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="завершен"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="оплачен")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="отменен"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="заказчик",
                    ),
                ),
                (
                    "item_ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_obj",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_provider",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created"],
            },
        ),
    ]
