# Generated by Django 5.0.4 on 2024-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Размещен заказчиком"),
                    ("in_progress", "В работе у исполнителя"),
                    ("cancelled_by_customer", "Отменен заказчиком"),
                    ("rejected_by_provider", "Отклонен исполнителем"),
                    ("submitted_by_provider", "Сдан исполнителем"),
                    ("returned_by_customer", "Возвращен заказчиком на доработку"),
                    ("accepted_by_customer", "Принят заказчиком"),
                    ("paid", "Оплачен"),
                    ("completed", "Завершен"),
                ],
                default="created",
                max_length=32,
                verbose_name="статус заказа",
            ),
        ),
    ]
