# Generated by Django 5.0.4 on 2024-05-02 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменен"),
                ),
            ],
            options={
                "verbose_name": "чат",
                "verbose_name_plural": "чаты",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=1500, verbose_name="Текст сообщения"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Файл, прилагаемый к сообщению.",
                        null=True,
                        upload_to="",
                        verbose_name="вложение",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Сообщение прочитано получателем.",
                        verbose_name="прочитано",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
            ],
            options={
                "verbose_name": "cообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["-created"],
            },
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="exchange_ca_title_5b7bb9_idx",
        ),
        migrations.AddField(
            model_name="chat",
            name="topic_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_obj",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="exchange.chat",
                verbose_name="чат",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="получатель",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="отправитель",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="latest_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_in_chat",
                to="exchange.message",
                verbose_name="Последнее сообщение",
            ),
        ),
    ]
